# mypy: ignore-errors

import typing

from _typeshed import Incomplete
from urwid.canvas import CompositeCanvas as CompositeCanvas

from .constants import Sizing as Sizing
from .widget import Widget as Widget
from .widget_decoration import WidgetDecoration as WidgetDecoration

class BoxAdapterError(Exception): ...

class BoxAdapter(WidgetDecoration):
    no_cache: typing.ClassVar[list[str]]
    height: Incomplete
    def __init__(self, box_widget, height) -> None: ...
    @property
    def box_widget(self) -> Widget: ...
    def sizing(self): ...
    def rows(self, size: tuple[int], focus: bool = ...) -> int: ...
    def get_cursor_coords(self, size: tuple[int]) -> int | None: ...
    def get_pref_col(self, size: tuple[int]) -> int | None: ...
    def keypress(self, size: tuple[int], key: str) -> str | None: ...
    def move_cursor_to_coords(self, size: tuple[int], col: int, row: int): ...
    def mouse_event(
        self, size: tuple[int], event, button: int, col: int, row: int, focus: bool
    ) -> bool: ...
    def render(self, size: tuple[int], focus: bool = ...) -> CompositeCanvas: ...
    def __getattr__(self, name: str): ...
