# mypy: ignore-errors

import abc
import typing
from collections.abc import Iterator

from .widget import Widget as Widget

class WidgetContainerMixin(metaclass=abc.ABCMeta):
    def __getitem__(self, position) -> Widget: ...
    def get_focus_path(self): ...
    def set_focus_path(self, positions) -> None: ...
    def get_focus_widgets(self) -> list[Widget]: ...
    @property
    @abc.abstractmethod
    def focus(self) -> Widget: ...

class WidgetContainerListContentsMixin(metaclass=abc.ABCMeta):
    def __iter__(self) -> Iterator[int]: ...
    def __reversed__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...
    @property
    @abc.abstractmethod
    def contents(self) -> list[tuple[Widget, typing.Any]]: ...
    @property
    @abc.abstractmethod
    def focus_position(self) -> int | None: ...
