# mypy: ignore-errors

import typing

from _typeshed import Incomplete
from typing_extensions import Literal
from urwid.canvas import CompositeCanvas as CompositeCanvas

from .widget import (
    Widget as Widget,
    delegate_to_widget_mixin as delegate_to_widget_mixin,
)

class WidgetDecoration(Widget):
    def __init__(self, original_widget: Widget) -> None: ...
    @property
    def original_widget(self) -> Widget: ...
    @property
    def base_widget(self) -> Widget: ...
    def selectable(self) -> bool: ...
    def sizing(self): ...

class WidgetPlaceholder(Incomplete, WidgetDecoration): ...

class WidgetDisable(WidgetDecoration):
    no_cache: typing.ClassVar[list[str]]
    ignore_focus: bool
    def selectable(self) -> Literal[False]: ...
    def rows(self, size, focus: bool = ...) -> int: ...
    def sizing(self): ...
    def pack(self, size, focus: bool = ...) -> tuple[int, int]: ...
    def render(self, size, focus: bool = ...) -> CompositeCanvas: ...
