import typing

from _typeshed import Incomplete
from typing_extensions import Literal
from urwid import util as util

TEMP_DIR: Incomplete
ALARM_DELAY: int
POLL_CONNECT: int
MAX_COLS: int
MAX_ROWS: int
MAX_READ: int
BUF_SZ: int

class Screen:
    palette: Incomplete
    has_color: bool
    def __init__(self) -> None: ...
    @property
    def started(self): ...
    def register_palette(self, palette) -> None: ...
    def register_palette_entry(
        self, name, foreground, background, mono: Incomplete | None = ...
    ) -> None: ...
    def set_mouse_tracking(self, enable: bool = ...) -> None: ...
    def tty_signal_keys(self, *args, **vargs) -> None: ...
    last_screen: Incomplete
    last_screen_width: int
    update_method: Incomplete
    pipe_name: Incomplete
    input_fd: Incomplete
    input_tail: str
    content_head: Incomplete
    def start(self): ...
    def stop(self) -> None: ...
    def set_input_timeouts(self, *args) -> None: ...
    def run_wrapper(self, fn): ...
    def draw_screen(self, size, r) -> None: ...
    def clear(self) -> None: ...
    def get_cols_rows(self): ...
    @typing.overload
    def get_input(self, raw_keys: Literal[False]) -> list[str]: ...
    @typing.overload
    def get_input(self, raw_keys: Literal[True]) -> tuple[list[str], list[int]]: ...

def code_span(s, fg, bg, cursor: int = ...): ...
def html_escape(text): ...
def is_web_request(): ...
def handle_short_request(): ...

class _Preferences:
    app_name: str
    pipe_dir: str
    allow_polling: bool
    max_clients: int
    def __init__(self, app_name, pipe_dir, allow_polling, max_clients) -> None: ...

def set_preferences(
    app_name: str,
    pipe_dir: str = ...,
    allow_polling: bool = ...,
    max_clients: int = ...,
) -> None: ...

class ErrorLog:
    errfile: Incomplete
    def __init__(self, errfile) -> None: ...
    def write(self, err) -> None: ...

def daemonize(errfile) -> None: ...
