name: Python app checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: docker://docker.io/sunpeek/poetry:py3.10-slim
      run: |
        poetry install
    - name: Check types with mypy
      run: |
        poetry run mypy --strict
    - name: Check Black style
      run: |
        poetry run black --check --diff .
    - name: Lint with flake8
      run: |
        poetry run flake8
    - name: Confirm that app runs
      run: |
        poetry run wwclock --version
